sudo: required
services: 
  - docker

before_install:
  - docker build -t aralagarsamy/apa-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aralagarsamy/apa-docker-react npm run test